/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarLoanCalculatorRouteImport } from './routes/car-loan-calculator'
import { Route as PtaTaxCalculatorRouteImport } from './routes/pta-tax-calculator'
import { Route as GovtSalaryCalculatorRouteImport } from './routes/govt-salary-calculator'
import { Route as PensionCalculatorRouteImport } from './routes/pension-calculator'
import { Route as MatricResultCalculatorRouteImport } from './routes/matric-result-calculator'
import { Route as GoldPriceCalculatorRouteImport } from './routes/gold-price-calculator'
import { Route as PropertySizeCalculatorRouteImport } from './routes/property-size-calculator'
import { Route as UmrahSavingsCalculatorRouteImport } from './routes/umrah-savings-calculator'
import { Route as InflationCalculatorRouteImport } from './routes/inflation-calculator'
import { Route as MedicineDoseCalculatorRouteImport } from './routes/medicine-dose-calculator'
import { Route as SleepCalculatorRouteImport } from './routes/sleep-calculator'
import { Route as DataUsageCalculatorRouteImport } from './routes/data-usage-calculator'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug.ts'
import { Route as ZakatCalculatorRouteImport } from './routes/zakat-calculator'
import { Route as WordCounterRouteImport } from './routes/word-counter'
import { Route as UnitConverterRouteImport } from './routes/unit-converter'
import { Route as TipCalculatorRouteImport } from './routes/tip-calculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaryTaxCalculatorRouteImport } from './routes/salary-tax-calculator'
import { Route as RandomNumberGeneratorRouteImport } from './routes/random-number-generator'
import { Route as ProfitLossCalculatorRouteImport } from './routes/profit-loss-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as PercentageCalculatorRouteImport } from './routes/percentage-calculator'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as IncomeTaxCalculatorRouteImport } from './routes/income-tax-calculator'
import { Route as HijriDateConverterRouteImport } from './routes/hijri-date-converter'
import { Route as GstCalculatorRouteImport } from './routes/gst-calculator'
import { Route as GpaToPercentageRouteImport } from './routes/gpa-to-percentage'
import { Route as FuelCostCalculatorRouteImport } from './routes/fuel-cost-calculator'
import { Route as ElectricityBillCalculatorRouteImport } from './routes/electricity-bill-calculator'
import { Route as DiscountCalculatorRouteImport } from './routes/discount-calculator'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DateDifferenceCalculatorRouteImport } from './routes/date-difference-calculator'
import { Route as CurrencyConverterRouteImport } from './routes/currency-converter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CgpaCalculatorRouteImport } from './routes/cgpa-calculator'
import { Route as CalorieCalculatorRouteImport } from './routes/calorie-calculator'
import { Route as BmiCalculatorRouteImport } from './routes/bmi-calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AttendanceCalculatorRouteImport } from './routes/attendance-calculator'
import { Route as AgeCalculatorRouteImport } from './routes/age-calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const CarLoanCalculatorRoute = CarLoanCalculatorRouteImport.update({ id: '/car-loan-calculator', path: '/car-loan-calculator', getParentRoute: () => rootRoute } as any)
const PtaTaxCalculatorRoute = PtaTaxCalculatorRouteImport.update({ id: '/pta-tax-calculator', path: '/pta-tax-calculator', getParentRoute: () => rootRoute } as any)
const GovtSalaryCalculatorRoute = GovtSalaryCalculatorRouteImport.update({ id: '/govt-salary-calculator', path: '/govt-salary-calculator', getParentRoute: () => rootRoute } as any)
const PensionCalculatorRoute = PensionCalculatorRouteImport.update({ id: '/pension-calculator', path: '/pension-calculator', getParentRoute: () => rootRoute } as any)
const MatricResultCalculatorRoute = MatricResultCalculatorRouteImport.update({ id: '/matric-result-calculator', path: '/matric-result-calculator', getParentRoute: () => rootRoute } as any)
const GoldPriceCalculatorRoute = GoldPriceCalculatorRouteImport.update({ id: '/gold-price-calculator', path: '/gold-price-calculator', getParentRoute: () => rootRoute } as any)
const PropertySizeCalculatorRoute = PropertySizeCalculatorRouteImport.update({ id: '/property-size-calculator', path: '/property-size-calculator', getParentRoute: () => rootRoute } as any)
const UmrahSavingsCalculatorRoute = UmrahSavingsCalculatorRouteImport.update({ id: '/umrah-savings-calculator', path: '/umrah-savings-calculator', getParentRoute: () => rootRoute } as any)
const InflationCalculatorRoute = InflationCalculatorRouteImport.update({ id: '/inflation-calculator', path: '/inflation-calculator', getParentRoute: () => rootRoute } as any)
const MedicineDoseCalculatorRoute = MedicineDoseCalculatorRouteImport.update({ id: '/medicine-dose-calculator', path: '/medicine-dose-calculator', getParentRoute: () => rootRoute } as any)
const SleepCalculatorRoute = SleepCalculatorRouteImport.update({ id: '/sleep-calculator', path: '/sleep-calculator', getParentRoute: () => rootRoute } as any)
const DataUsageCalculatorRoute = DataUsageCalculatorRouteImport.update({ id: '/data-usage-calculator', path: '/data-usage-calculator', getParentRoute: () => rootRoute } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({ id: '/blog/$slug', path: '/blog/$slug', getParentRoute: () => rootRoute } as any)
const ZakatCalculatorRoute = ZakatCalculatorRouteImport.update({
  id: '/zakat-calculator',
  path: '/zakat-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const WordCounterRoute = WordCounterRouteImport.update({
  id: '/word-counter',
  path: '/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const TipCalculatorRoute = TipCalculatorRouteImport.update({
  id: '/tip-calculator',
  path: '/tip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryTaxCalculatorRoute = SalaryTaxCalculatorRouteImport.update({
  id: '/salary-tax-calculator',
  path: '/salary-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomNumberGeneratorRoute = RandomNumberGeneratorRouteImport.update({
  id: '/random-number-generator',
  path: '/random-number-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitLossCalculatorRoute = ProfitLossCalculatorRouteImport.update({
  id: '/profit-loss-calculator',
  path: '/profit-loss-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageCalculatorRoute = PercentageCalculatorRouteImport.update({
  id: '/percentage-calculator',
  path: '/percentage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeTaxCalculatorRoute = IncomeTaxCalculatorRouteImport.update({
  id: '/income-tax-calculator',
  path: '/income-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HijriDateConverterRoute = HijriDateConverterRouteImport.update({
  id: '/hijri-date-converter',
  path: '/hijri-date-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const GstCalculatorRoute = GstCalculatorRouteImport.update({
  id: '/gst-calculator',
  path: '/gst-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaToPercentageRoute = GpaToPercentageRouteImport.update({
  id: '/gpa-to-percentage',
  path: '/gpa-to-percentage',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelCostCalculatorRoute = FuelCostCalculatorRouteImport.update({
  id: '/fuel-cost-calculator',
  path: '/fuel-cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricityBillCalculatorRoute =
  ElectricityBillCalculatorRouteImport.update({
    id: '/electricity-bill-calculator',
    path: '/electricity-bill-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscountCalculatorRoute = DiscountCalculatorRouteImport.update({
  id: '/discount-calculator',
  path: '/discount-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DateDifferenceCalculatorRoute =
  DateDifferenceCalculatorRouteImport.update({
    id: '/date-difference-calculator',
    path: '/date-difference-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurrencyConverterRoute = CurrencyConverterRouteImport.update({
  id: '/currency-converter',
  path: '/currency-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaCalculatorRoute = CgpaCalculatorRouteImport.update({
  id: '/cgpa-calculator',
  path: '/cgpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalorieCalculatorRoute = CalorieCalculatorRouteImport.update({
  id: '/calorie-calculator',
  path: '/calorie-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiCalculatorRoute = BmiCalculatorRouteImport.update({
  id: '/bmi-calculator',
  path: '/bmi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceCalculatorRoute = AttendanceCalculatorRouteImport.update({
  id: '/attendance-calculator',
  path: '/attendance-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeCalculatorRoute = AgeCalculatorRouteImport.update({
  id: '/age-calculator',
  path: '/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/blog': typeof BlogRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
  '/calorie-calculator': typeof CalorieCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference-calculator': typeof DateDifferenceCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/discount-calculator': typeof DiscountCalculatorRoute
  '/electricity-bill-calculator': typeof ElectricityBillCalculatorRoute
  '/fuel-cost-calculator': typeof FuelCostCalculatorRoute
  '/gpa-to-percentage': typeof GpaToPercentageRoute
  '/gst-calculator': typeof GstCalculatorRoute
  '/hijri-date-converter': typeof HijriDateConverterRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/privacy': typeof PrivacyRoute
  '/profit-loss-calculator': typeof ProfitLossCalculatorRoute
  '/random-number-generator': typeof RandomNumberGeneratorRoute
  '/salary-tax-calculator': typeof SalaryTaxCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tip-calculator': typeof TipCalculatorRoute
  '/unit-converter': typeof UnitConverterRoute
  '/word-counter': typeof WordCounterRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/blog': typeof BlogRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
  '/calorie-calculator': typeof CalorieCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference-calculator': typeof DateDifferenceCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/discount-calculator': typeof DiscountCalculatorRoute
  '/electricity-bill-calculator': typeof ElectricityBillCalculatorRoute
  '/fuel-cost-calculator': typeof FuelCostCalculatorRoute
  '/gpa-to-percentage': typeof GpaToPercentageRoute
  '/gst-calculator': typeof GstCalculatorRoute
  '/hijri-date-converter': typeof HijriDateConverterRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/privacy': typeof PrivacyRoute
  '/profit-loss-calculator': typeof ProfitLossCalculatorRoute
  '/random-number-generator': typeof RandomNumberGeneratorRoute
  '/salary-tax-calculator': typeof SalaryTaxCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tip-calculator': typeof TipCalculatorRoute
  '/unit-converter': typeof UnitConverterRoute
  '/word-counter': typeof WordCounterRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/attendance-calculator': typeof AttendanceCalculatorRoute
  '/blog': typeof BlogRoute
  '/bmi-calculator': typeof BmiCalculatorRoute
  '/calorie-calculator': typeof CalorieCalculatorRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference-calculator': typeof DateDifferenceCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/discount-calculator': typeof DiscountCalculatorRoute
  '/electricity-bill-calculator': typeof ElectricityBillCalculatorRoute
  '/fuel-cost-calculator': typeof FuelCostCalculatorRoute
  '/gpa-to-percentage': typeof GpaToPercentageRoute
  '/gst-calculator': typeof GstCalculatorRoute
  '/hijri-date-converter': typeof HijriDateConverterRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/privacy': typeof PrivacyRoute
  '/profit-loss-calculator': typeof ProfitLossCalculatorRoute
  '/random-number-generator': typeof RandomNumberGeneratorRoute
  '/salary-tax-calculator': typeof SalaryTaxCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tip-calculator': typeof TipCalculatorRoute
  '/unit-converter': typeof UnitConverterRoute
  '/word-counter': typeof WordCounterRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/age-calculator'
    | '/attendance-calculator'
    | '/blog'
    | '/bmi-calculator'
    | '/calorie-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/currency-converter'
    | '/date-difference-calculator'
    | '/disclaimer'
    | '/discount-calculator'
    | '/electricity-bill-calculator'
    | '/fuel-cost-calculator'
    | '/gpa-to-percentage'
    | '/gst-calculator'
    | '/hijri-date-converter'
    | '/income-tax-calculator'
    | '/loan-calculator'
    | '/password-generator'
    | '/percentage-calculator'
    | '/prayer-times'
    | '/privacy'
    | '/profit-loss-calculator'
    | '/random-number-generator'
    | '/salary-tax-calculator'
    | '/sitemap.xml'
    | '/tip-calculator'
    | '/unit-converter'
    | '/word-counter'
    | '/zakat-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/age-calculator'
    | '/attendance-calculator'
    | '/blog'
    | '/bmi-calculator'
    | '/calorie-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/currency-converter'
    | '/date-difference-calculator'
    | '/disclaimer'
    | '/discount-calculator'
    | '/electricity-bill-calculator'
    | '/fuel-cost-calculator'
    | '/gpa-to-percentage'
    | '/gst-calculator'
    | '/hijri-date-converter'
    | '/income-tax-calculator'
    | '/loan-calculator'
    | '/password-generator'
    | '/percentage-calculator'
    | '/prayer-times'
    | '/privacy'
    | '/profit-loss-calculator'
    | '/random-number-generator'
    | '/salary-tax-calculator'
    | '/sitemap.xml'
    | '/tip-calculator'
    | '/unit-converter'
    | '/word-counter'
    | '/zakat-calculator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/age-calculator'
    | '/attendance-calculator'
    | '/blog'
    | '/bmi-calculator'
    | '/calorie-calculator'
    | '/cgpa-calculator'
    | '/contact'
    | '/currency-converter'
    | '/date-difference-calculator'
    | '/disclaimer'
    | '/discount-calculator'
    | '/electricity-bill-calculator'
    | '/fuel-cost-calculator'
    | '/gpa-to-percentage'
    | '/gst-calculator'
    | '/hijri-date-converter'
    | '/income-tax-calculator'
    | '/loan-calculator'
    | '/password-generator'
    | '/percentage-calculator'
    | '/prayer-times'
    | '/privacy'
    | '/profit-loss-calculator'
    | '/random-number-generator'
    | '/salary-tax-calculator'
    | '/sitemap.xml'
    | '/tip-calculator'
    | '/unit-converter'
    | '/word-counter'
    | '/zakat-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgeCalculatorRoute: typeof AgeCalculatorRoute
  AttendanceCalculatorRoute: typeof AttendanceCalculatorRoute
  BlogRoute: typeof BlogRoute
  BmiCalculatorRoute: typeof BmiCalculatorRoute
  CalorieCalculatorRoute: typeof CalorieCalculatorRoute
  CgpaCalculatorRoute: typeof CgpaCalculatorRoute
  ContactRoute: typeof ContactRoute
  CurrencyConverterRoute: typeof CurrencyConverterRoute
  DateDifferenceCalculatorRoute: typeof DateDifferenceCalculatorRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DiscountCalculatorRoute: typeof DiscountCalculatorRoute
  ElectricityBillCalculatorRoute: typeof ElectricityBillCalculatorRoute
  FuelCostCalculatorRoute: typeof FuelCostCalculatorRoute
  GpaToPercentageRoute: typeof GpaToPercentageRoute
  GstCalculatorRoute: typeof GstCalculatorRoute
  HijriDateConverterRoute: typeof HijriDateConverterRoute
  IncomeTaxCalculatorRoute: typeof IncomeTaxCalculatorRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PercentageCalculatorRoute: typeof PercentageCalculatorRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfitLossCalculatorRoute: typeof ProfitLossCalculatorRoute
  RandomNumberGeneratorRoute: typeof RandomNumberGeneratorRoute
  SalaryTaxCalculatorRoute: typeof SalaryTaxCalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TipCalculatorRoute: typeof TipCalculatorRoute
  UnitConverterRoute: typeof UnitConverterRoute
  WordCounterRoute: typeof WordCounterRoute
  ZakatCalculatorRoute: typeof ZakatCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakat-calculator': {
      id: '/zakat-calculator'
      path: '/zakat-calculator'
      fullPath: '/zakat-calculator'
      preLoaderRoute: typeof ZakatCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-counter': {
      id: '/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof WordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-converter': {
      id: '/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tip-calculator': {
      id: '/tip-calculator'
      path: '/tip-calculator'
      fullPath: '/tip-calculator'
      preLoaderRoute: typeof TipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-tax-calculator': {
      id: '/salary-tax-calculator'
      path: '/salary-tax-calculator'
      fullPath: '/salary-tax-calculator'
      preLoaderRoute: typeof SalaryTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-number-generator': {
      id: '/random-number-generator'
      path: '/random-number-generator'
      fullPath: '/random-number-generator'
      preLoaderRoute: typeof RandomNumberGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-loss-calculator': {
      id: '/profit-loss-calculator'
      path: '/profit-loss-calculator'
      fullPath: '/profit-loss-calculator'
      preLoaderRoute: typeof ProfitLossCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage-calculator': {
      id: '/percentage-calculator'
      path: '/percentage-calculator'
      fullPath: '/percentage-calculator'
      preLoaderRoute: typeof PercentageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-tax-calculator': {
      id: '/income-tax-calculator'
      path: '/income-tax-calculator'
      fullPath: '/income-tax-calculator'
      preLoaderRoute: typeof IncomeTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijri-date-converter': {
      id: '/hijri-date-converter'
      path: '/hijri-date-converter'
      fullPath: '/hijri-date-converter'
      preLoaderRoute: typeof HijriDateConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-calculator': {
      id: '/gst-calculator'
      path: '/gst-calculator'
      fullPath: '/gst-calculator'
      preLoaderRoute: typeof GstCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-to-percentage': {
      id: '/gpa-to-percentage'
      path: '/gpa-to-percentage'
      fullPath: '/gpa-to-percentage'
      preLoaderRoute: typeof GpaToPercentageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-cost-calculator': {
      id: '/fuel-cost-calculator'
      path: '/fuel-cost-calculator'
      fullPath: '/fuel-cost-calculator'
      preLoaderRoute: typeof FuelCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricity-bill-calculator': {
      id: '/electricity-bill-calculator'
      path: '/electricity-bill-calculator'
      fullPath: '/electricity-bill-calculator'
      preLoaderRoute: typeof ElectricityBillCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-calculator': {
      id: '/discount-calculator'
      path: '/discount-calculator'
      fullPath: '/discount-calculator'
      preLoaderRoute: typeof DiscountCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-difference-calculator': {
      id: '/date-difference-calculator'
      path: '/date-difference-calculator'
      fullPath: '/date-difference-calculator'
      preLoaderRoute: typeof DateDifferenceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-converter': {
      id: '/currency-converter'
      path: '/currency-converter'
      fullPath: '/currency-converter'
      preLoaderRoute: typeof CurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa-calculator': {
      id: '/cgpa-calculator'
      path: '/cgpa-calculator'
      fullPath: '/cgpa-calculator'
      preLoaderRoute: typeof CgpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calorie-calculator': {
      id: '/calorie-calculator'
      path: '/calorie-calculator'
      fullPath: '/calorie-calculator'
      preLoaderRoute: typeof CalorieCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi-calculator': {
      id: '/bmi-calculator'
      path: '/bmi-calculator'
      fullPath: '/bmi-calculator'
      preLoaderRoute: typeof BmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-calculator': {
      id: '/attendance-calculator'
      path: '/attendance-calculator'
      fullPath: '/attendance-calculator'
      preLoaderRoute: typeof AttendanceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-calculator': {
      id: '/age-calculator'
      path: '/age-calculator'
      fullPath: '/age-calculator'
      preLoaderRoute: typeof AgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgeCalculatorRoute: AgeCalculatorRoute,
  AttendanceCalculatorRoute: AttendanceCalculatorRoute,
  BlogRoute: BlogRoute,
  BmiCalculatorRoute: BmiCalculatorRoute,
  CalorieCalculatorRoute: CalorieCalculatorRoute,
  CgpaCalculatorRoute: CgpaCalculatorRoute,
  ContactRoute: ContactRoute,
  CurrencyConverterRoute: CurrencyConverterRoute,
  DateDifferenceCalculatorRoute: DateDifferenceCalculatorRoute,
  DisclaimerRoute: DisclaimerRoute,
  DiscountCalculatorRoute: DiscountCalculatorRoute,
  ElectricityBillCalculatorRoute: ElectricityBillCalculatorRoute,
  FuelCostCalculatorRoute: FuelCostCalculatorRoute,
  GpaToPercentageRoute: GpaToPercentageRoute,
  GstCalculatorRoute: GstCalculatorRoute,
  HijriDateConverterRoute: HijriDateConverterRoute,
  IncomeTaxCalculatorRoute: IncomeTaxCalculatorRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PercentageCalculatorRoute: PercentageCalculatorRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfitLossCalculatorRoute: ProfitLossCalculatorRoute,
  RandomNumberGeneratorRoute: RandomNumberGeneratorRoute,
  SalaryTaxCalculatorRoute: SalaryTaxCalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TipCalculatorRoute: TipCalculatorRoute,
  UnitConverterRoute: UnitConverterRoute,
  WordCounterRoute: WordCounterRoute,
  ZakatCalculatorRoute: ZakatCalculatorRoute,
  CarLoanCalculatorRoute: CarLoanCalculatorRoute,
  PtaTaxCalculatorRoute: PtaTaxCalculatorRoute,
  GovtSalaryCalculatorRoute: GovtSalaryCalculatorRoute,
  PensionCalculatorRoute: PensionCalculatorRoute,
  MatricResultCalculatorRoute: MatricResultCalculatorRoute,
  GoldPriceCalculatorRoute: GoldPriceCalculatorRoute,
  PropertySizeCalculatorRoute: PropertySizeCalculatorRoute,
  UmrahSavingsCalculatorRoute: UmrahSavingsCalculatorRoute,
  InflationCalculatorRoute: InflationCalculatorRoute,
  MedicineDoseCalculatorRoute: MedicineDoseCalculatorRoute,
  SleepCalculatorRoute: SleepCalculatorRoute,
  DataUsageCalculatorRoute: DataUsageCalculatorRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// New tools added - these will be auto-registered on next build
// Car Loan, PTA Tax, Govt Salary, Pension, Matric Result, Gold, Property, Umrah, Inflation, Medicine, Sleep, Data Usage
